services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 5000:5000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443


# sudo certbot certonly --standalone -d fume.ddns.net

# - Congratulations! Your certificate and chain have been saved at:
#   /etc/letsencrypt/live/fume.ddns.net/fullchain.pem
#   Your key file has been saved at:
#   /etc/letsencrypt/live/fume.ddns.net/privkey.pem
#   Your certificate will expire on 2024-09-11. To obtain a new or
#   tweaked version of this certificate in the future, simply run
#   certbot again. To non-interactively renew *all* of your
#   certificates, run "certbot renew"